### PR TITLE
[docs/chinese] Translate official document to Chinese(Simplified)

### PR DESCRIPTION
**Pull request by QC-L**
Hello, guys. We have completed the translation of all the documents.

- [x] [introduction](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction)
  - [x] [core-concepts](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/core-concepts.md)
  - [x] [getting-started](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/getting-started.mdx)
  - [x] [installation](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/installation.md)
  - [x] [motivation](https://github.com/docschina/Recoil/tree/docs/docs/docs/introduction/motivation.md)
- [x] [basic-tutorial](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial)
  - [x] [selectors](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial/selectors.md)
  - [x] [intro](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial/intro.md)
  - [x] [atoms](https://github.com/docschina/Recoil/tree/docs/docs/docs/basic-tutorial/atoms.mdx)
- [x] [api-reference](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference)
  - [x] [core](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core)
    - [x] [useRecoilBridgeAcrossReactRoots](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilBridgeAcrossReactRoots.md) (@QC-L) [PR 70](https://github.com/docschina/Recoil/pull/70)
    - [x] [atom](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/atom.md)
    - [x] [isRecoilValue](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/isRecoilValue.md)
    - [x] [Loadable](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/Loadable.md) (@KimYangOfCat) [PR 67](https://github.com/docschina/Recoil/pull/67) 
    - [x] [RecoilRoot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/RecoilRoot.md)
    - [x] [selector](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/selector.md) (@KnowsCount) [PR 65](https://github.com/docschina/Recoil/pull/65) 
    - [x] [Snapshot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/Snapshot.md) (@KnowsCount) [PR 87](https://github.com/docschina/Recoil/pull/87)
    - [x] [useGetRecoilValueInfo](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useGetRecoilValueInfo.md) (@KimYangOfCat) [PR 68](https://github.com/docschina/Recoil/pull/68) 
    - [x] [useGotoRecoilSnapshot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useGotoRecoilSnapshot.md) (@KimYangOfCat) [PR 66](https://github.com/docschina/Recoil/pull/66) 
    - [x] [useRecoilCallback](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilCallback.md)  (@KnowsCount)
    - [x] [useRecoilSnapshot](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilSnapshot.md) (@KimYangOfCat) [PR 81](https://github.com/docschina/Recoil/pull/81) 
    - [x] [useRecoilState](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilState.md)
    - [x] [useRecoilStateLoadable](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilStateLoadable.md) (@KnowsCount) [PR 78](https://github.com/docschina/Recoil/pull/78)
    - [x] [useRecoilTransactionObserver](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilTransactionObserver.md) (@KimYangOfCat) [PR 71](https://github.com/docschina/Recoil/pull/71) 
    - [x] [useRecoilValue](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilValue.md)
    - [x] [useRecoilValueLoadable](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useRecoilValueLoadable.md) (@Ivocin) [PR 85](https://github.com/docschina/Recoil/pull/85) 
    - [x] [useResetRecoilState](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useResetRecoilState.md)
    - [x] [useSetRecoilState](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/core/useSetRecoilState.md)
  - [x] [utils](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils)
    - [x] [waitForNone](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForNone.md) (@KimYangOfCat) [PR 82](https://github.com/docschina/Recoil/pull/82) 
    - [x] [atomFamily](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/atomFamily.md) (@KnowsCount)
    - [x] [constSelector](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/constSelector.md) (@KnowsCount) [PR 77](https://github.com/docschina/Recoil/pull/77)
    - [x] [errorSelector](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/errorSelector.md) (@KimYangOfCat) [PR 72](https://github.com/docschina/Recoil/pull/72) 
    - [x] [noWait](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/noWait.md) (@KimYangOfCat) [PR 83](https://github.com/docschina/Recoil/pull/83) 
    - [x] [selectorFamily](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/selectorFamily.md) (@KimYangOfCat) [PR 84](https://github.com/docschina/Recoil/pull/84) 
    - [x] [waitForAll](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForAll.md) (@KimYangOfCat) [PR 75](https://github.com/docschina/Recoil/pull/75) 
    - [x] [waitForAllSettled](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForAllSettled.md) (@KimYangOfCat) [PR 74](https://github.com/docschina/Recoil/pull/74) 
    - [x] [waitForAny](https://github.com/docschina/Recoil/tree/docs/docs/docs/api-reference/utils/waitForAny.md) (@KimYangOfCat) [PR 73](https://github.com/docschina/Recoil/pull/73) 
- [x] [guides](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides)
  - [x] [asynchronous-data-queries](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/asynchronous-data-queries.md) (@KimYangOfCat ) [PR 95](https://github.com/docschina/Recoil/pull/95) 
  - [x] [atom-effects](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/atom-effects.md) (@KnowsCount) [PR 92](https://github.com/docschina/Recoil/pull/92)
  - [x] [dev-tools](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/dev-tools.md) (@wjq990112) [PR 80](https://github.com/docschina/Recoil/pull/80) 
  - [x] [testing](https://github.com/docschina/Recoil/tree/docs/docs/docs/guides/testing.md) (@KimYangOfCat) [PR 69](https://github.com/docschina/Recoil/pull/69)

### CODE REVIEW

**Comment by mondaychen** [comment]
Thank you all for the contribution! This is awesome. I will review now.

**Review by mondaychen — CHANGES_REQUESTED** [review]
Thanks for the PR. It is very comprehensive and high quality. I have some suggestions for a part of it.

**Comment by vickmeng** [comment]
thx，very helpful.
And I want to know how to join the translation team?

**Comment by KnowsCount** [comment]
@vickmeng you could always visit our [organisation](https://github.com/docschina) to find out more.

**Pull request merged**
