### PR TITLE
[docs] Add new logo and new branded elements

### LINKED ISSUE #10: Logo
An idea of a logo? 

I can help if you want :)

### PR DESCRIPTION
**Pull request by graypegg**
From discussion with @drarmstr and @vjeux

wordmark

It sounds like we have a new logo! I've included source files + samples in /logo
  - [x] The original illustrator files would be great to allow for potential future derived images/logos/artwork/…
  - [x] Image files for the logo at various resolutions **(I've included the SVG/tweaked versions for S/XS sizes for this)**
  - [x] Image files for logo+Recoil at various resolutions **(I've included the SVG for this)**
  - [x] Images for the docs sections (Data-Flow Graph, Cross-App Observation)
  - [x] Icon file for the browser tab, chrome dev tools, …
  
as well as updated the docs theme with the design shown in the email thread /w @vjeux and @drarmstr 
  
Capture d’écran, le 2021-03-21 à 23 48 15
Capture d’écran, le 2021-03-21 à 23 48 17

This PR would close #10

### CODE REVIEW

**Comment by graypegg** [comment]
Oops sorry, I knew I needed to do that 🤦

**Comment by vjeux** [comment]
This is so awesome! Thanks so much <3

**Comment by mondaychen** [comment]
Thank you for your amazing work and generous contribution!

**Comment by LOGANLEEE** [comment]
this dev tool doesn't work on chrome with error.

100% fatal error

**Pull request merged**
