### PR TITLE
Pack all JS files in dist folder

### PR DESCRIPTION
**Pull request by dustinsoftware**
This was an oversight from #67

### CODE REVIEW

**Comment by dustinsoftware** [comment]
#33 also addresses this; if that lands first this can be closed.

**Comment by dustinsoftware** [comment]
FWIW there is a fair amount of discussion on #33 so on second thought, landing this sooner would unblock releasing the current `master` branch.  cc @vjeux

**Comment by vjeux** [comment]
This makes sense

**Comment by dustinsoftware** [comment]
#195 appears to be a duplicate PR, should we land one of them soon?

**Comment by dustinsoftware** [comment]
This landed in master, closing.

**Pull request closed without merging**
