### PR TITLE
Fix  onSet param type

### PR DESCRIPTION
**Pull request by linguofeng**
`newValue` call by `useResetRecoilState` is `DefaultValue` type

### CODE REVIEW

**Comment by drarmstr** [comment]
Do you have an example where `DefaultValue` is actually being provided for this parameter?  The interface was updated so that it should provide the actual default value itself in this parameter when the atom is reset instead of the `DefaultValue` placeholder.

**Comment by linguofeng** [comment]
> Do you have an example where `DefaultValue` is actually being provided for this parameter? The interface was updated so that it should provide the actual default value itself in this parameter when the atom is reset instead of the `DefaultValue` placeholder.

```ts
export const TOKEN_KEY = 'token-key';

export const tokenState = atom<string>({
  key: 'tokenState',
  default: '',
  effects_UNSTABLE: [
    ({ setSelf, onSet }) => {
      const token = localStorage.getItem(TOKEN_KEY);
      if (token) {
        setSelf(JSON.parse(token));
      }
-     onSet(token => { // token is string type, The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.ts(2358)
+     onSet((token: string | DefaultValue) => { // is OK
        if (token instanceof DefaultValue) {
          localStorage.removeItem(TOKEN_KEY);
        } else {
          localStorage.setItem(TOKEN_KEY, JSON.stringify(token));
        }
      });
    },
  ],
});

```

**Comment by linguofeng** [comment]
ref https://github.com/facebookexperimental/Recoil/blob/85f62d75c7250df84e27ad37acf374754e1116c5/typescript/index.d.ts#L365

**Comment by drarmstr** [comment]
With #1059 this check is no longer meaningful as `DefaultValue` is not used for the new value as the actual default value is used. 
```jsx
        if (token instanceof DefaultValue) {
          localStorage.removeItem(TOKEN_KEY);
```
The current interface doesn't distinguish between observing resetting an atom and setting an atom to an equivalent value.  If you would like to make that distinction you could use `getInfo_UNSTABLE()` in the effect from #1210 (not yet landed).  Open to ideas for a more elegant approach.

**Pull request closed without merging**
