### PR TITLE
Do not cause Batcher update while call getRecoilValueAsLoadable

### PR DESCRIPTION
**Pull request by markstock7**
trying to fix https://github.com/facebookexperimental/Recoil/issues/12

before the commit , test will report the following warning.

image

after this commit 

image

### CODE REVIEW

**Comment by mondaychen** [comment]
@davidmccabe @drarmstr

**Comment by desmap** [comment]
@davidmccabe @drarmstr When will this be merged and released? Thanks

**Comment by drarmstr** [comment]
Thank you so much for looking into this issue and trying to fix it!  One of the goals of Recoil is to work with React Concurrent Mode.  As part of that effort we are working on a diff that removes the data-flow graph of dependencies out of the  `TreeState`.  This change avoids updating state, and thus causing Batcher updates, during reads, and I think actually obviates the need for this PR.  We are getting closer to being able to land that..

**Comment by desmap** [comment]
@drarmstr thanks for the quick reply and I am looking fwd!

**Comment by markstock7** [comment]
> Thank you so much for looking into this issue and trying to fix it! One of the goals of Recoil is to work with React Concurrent Mode. As part of that effort we are working on a diff that removes the data-flow graph of dependencies out of the `TreeState`. This change avoids updating state, and thus causing Batcher updates, during reads, and I think actually obviates the need for this PR. We are getting closer to being able to land that..

it there any way that I can know the new implementation in advance？

**Comment by drarmstr** [comment]
We're just moving the data-flow graph from `TreeState` to `StoreState`, with versioning.

**Comment by jonthomp** [comment]
@drarmstr would the solution in this MR work in the short-term, or does it have potential issues in itself?

**Comment by drarmstr** [comment]
The diff has landed in master, so closing this now.

**Comment by mrlubos** [comment]
Hi @drarmstr, any update on the ETA for `0.0.11`? Thanks!

**Pull request closed without merging**
