### PR TITLE
Avoid window reference error in SSR

### PR DESCRIPTION
**Pull request by sbaudray**
Fixes https://github.com/facebookexperimental/Recoil/issues/34

### CODE REVIEW

**Comment by andreastoermer** [comment]
I think the code is wrong.

```
if (typeof window === 'undefined') {
    return false;
  }
```

If window is undefined, then we are in Node and not in Browser. So the correct result must be:

```
if (window === 'undefined') {
    return true;
}
```

**Comment by sbaudray** [comment]
`window === 'undefined'` throws a `ReferenceError` because `window` is not a valid reference. `typeof` returns `undefined` when the reference is not valid.

**Comment by andreastoermer** [comment]
ok, base on your response, my meaning is the same:

the check must be:

```
if (typeof window === 'undefined') {
    return true;
}
```

in node window is undefined, in browser not. the function name is isNode, so window must be undefined, if you will response the true answer for a isNode check.

**Comment by sbaudray** [comment]
`isNode` doesn't refer to nodejs but to DOM Nodes as commented here: https://github.com/facebookexperimental/Recoil/blob/c38012d92a292a4a867163cf7b14cfb3debddf01/src/util/Recoil_deepFreezeValue.js#L45

**Comment by andreastoermer** [comment]
Ok, but then maybe it's better to rename to function to isDomNode.

**Comment by vjeux** [comment]
Thanks!

**Pull request merged**
