### PR TITLE
[docs/french] Translate official document to French

### PR DESCRIPTION
**Pull request by fguitton**
- [x] docs
   - [x]  Introduction
      - [x]  Motivation
      - [x]  Core Concepts
      - [x]  Installation
      - [x]  Getting Started
   - [x]  Basic Tutorial
      - [x]  Intro
      - [x]  Atoms
      - [x]  Selectors
      - [x]  Bonus: Performance (Didn't release)
   - [x]  Guides
      - [x]  Asynchronous Data Queries
      - [x]  State Persistence
   - [x]  API Reference
      - [x]  Core
         - [x]  <RecoilRoot />
         - [x]  atom()
         - [x]  selector()
         - [x]  isRecoilValue()
      - [x]  Hooks
         - [x]  useRecoilState()
         - [x]  useRecoilValue()
         - [x]  useSetRecoilState()()
         - [x]  useResetRecoilState()()
         - [x]  useRecoilValueLoadable()()
         - [x]  useRecoilStateLoadable()()
         - [x]  useRecoilCallback()()
      - [x] Utils
         - [x]  atomFamily()
         - [x]  selectorFamily()
         - [x]  constSelector()
         - [x]  errorSelector()
         - [x]  noWait()
         - [x]  waitForAll()
         - [x]  waitForAny()
         - [x]  waitForNone()

### CODE REVIEW

**Comment by fguitton** [comment]
@drarmstr I'm going to proceed with translating what's left to translate in the coming few days, once that's done I'll be marking this ready for review.

**Comment by fguitton** [comment]
@drarmstr I believe I have completed the first treatment of the documentation including the latest changes from the `docs` branch. There might be the need to pass over this again with a refreshed eye but all of the topics have been translated to french.

**Comment by fguitton** [comment]
@drarmstr, @Mark-Yoo, I have worked in the last commit (31076a5) on making things compile with the french Markdown.
You will see that running `docusaurus build` now builds for both language and produces a `build` folder containing everything (See below).

I realise now that the other pages will probably have to be dealt with differently, probably relying on the `<Translate />` component and the JSON language files.

What are your thoughts ?

image

**Comment by drarmstr** [comment]
@fguitton - Oh, this looks promising!  looks like a single `yarn build` will build for all languages.  Can you clarify if this solves how the end user would access the translations?

**Comment by fguitton** [comment]
@drarmstr That's correct, everything gets built with a single `yarn build` command. I then served everything with `serve .\build\` to test everything worked appropriately. Although, in development mode (when using `yarn start`) one must apparently select which locale they want Docusaurus to serve, like so: `yarn start -- --locale fr`.

Regarding what it will be for users, I am directly making use of the built-in locale selector :
There is a couple of different positions to chose from, I found https://reactjs.org and https://docusaurus.io had their own locale menu in the top right so I went for the same.
https://github.com/facebookexperimental/Recoil/blob/3a76d01618dbbfc4f14a772dbfb8c205ad1cce71/docs/docusaurus.config.js#L69-L72

And this yields the following screen:
image

 _(I also noticed the latter had historical version documentation as well, something Recoil could leverage later ?)_

**Comment by drarmstr** [comment]
Excellent @fguitton, this looks exactly like what we need!  I'm catching up now after getting back to work.  Is everything here look good for merging the PR now?  Could we then merge #892 right after this?

**Comment by Mark-Yoo** [comment]
@drarmstr All Korean translations are merged into #18 instead of #892. so you can merge #18, not #892.
#892 will be closed after the #18 is merged :)

**Comment by drarmstr** [comment]
> @drarmstr All Korean translations are merged into #18 instead of #892. so you can merge #18, not #892.
> #892 will be closed after the #18 is merged :)

Great, thanks!  Ok, then I'll merge this and then #18 after getting the go-ahead from @fguitton .

**Comment by alstn2468** [comment]
@fguitton How can we pass translation data in the `index.js` file in the `pages` folder?

**Comment by fguitton** [comment]
@drarmstr, Yes, this is fully ready now It's a green light for me. I took the liberty to add the extra commit to translate the home (`index.js`) and resources (`resources.js`) pages as well. Giving us something like below. @alstn2468, you can see how I've gotten that done via the `<Translate />` API on commit ee541043

image

**Comment by drarmstr** [comment]
@fguitton - The French translation is now live!  Merci!

**Pull request merged**
