### PR TITLE
[docs/chinese] Translate official document to Chinese(Simplified)

### PR DESCRIPTION
**Pull request by Sunnysit**
Starts the translation to Chinese. The translation files are under docs/docs/docs_zh-cn/ directory. This is the progress:

- [ ]  docs
  - [ ]  Introduction
    - [x]  Motivation
    - [ ]  Core Concepts
    - [x]  Installation
    - [x]  Getting Started
  - [ ]  Basic Tutorial
    - [ ]  Intro
    - [ ]  Atoms
    - [ ]  Selectors
  - [ ]  Guides
    - [ ]  Asynchronous Data Queries
    - [ ]  State Persistence
  - [ ]  API Reference
    - [ ]  Core
    - [ ]  atom()
    - [ ]  selector()
    - [ ]  isRecoilValue()
    - [ ]  Hooks
    - [ ]  useRecoilState()
    - [ ]  useRecoilValue()
    - [ ]  useSetRecoilState()()
    - [ ]  useResetRecoilState()()
    - [ ]  useRecoilValueLoadable()()
    - [ ]  useRecoilStateLoadable()()
    - [ ]  useRecoilCallback()()
  - [ ]  Utils
    - [ ]  atomFamily()
    - [ ]  selectorFamily()
    - [ ]  constSelector()
    - [ ]  errorSelector()
    - [ ]  noWait()
    - [ ]  waitForAll()
    - [ ]  waitForAny()
    - [ ]  waitForNone()

### CODE REVIEW

**Comment by QC-L** [comment]
recoil.docschina.org

**Comment by Sunnysit** [comment]
@QC-L 

> Hey guys, I work with reactjs/zh-hans.
> 
> https://recoil.docschina.org
> Most of them have been translated, and the documents have been deployed.
> The repo under the [docschina](https://github.com/docschina/Recoil) organization.
> Synchronization way is the same as [reactjs.org](https://github.com/reactjs/zh-hans.reactjs.org).
> If you use the form of a folder, it is not easy to synchronize.
> 
> @Sunnysit @drarmstr



> Hey guys, I work with reactjs/zh-hans.
> 
> https://recoil.docschina.org
> Most of them have been translated, and the documents have been deployed.
> The repo under the [docschina](https://github.com/docschina/Recoil) organization.
> Synchronization way is the same as [reactjs.org](https://github.com/reactjs/zh-hans.reactjs.org).
> If you use the form of a folder, it is not easy to synchronize.
> 
> @Sunnysit @drarmstr

@QC-L Wow, that's awesome, you guys already translated all the docs. I guess I can close my pull request.

**Comment by QC-L** [comment]
@Sunnysit We can translate together.

**Comment by Sunnysit** [comment]
@QC-L  Yeah, I would like to help with the translatition if possible.

**Comment by QC-L** [comment]
@Sunnysit How to contact you? wechat or twitter?

**Comment by Sunnysit** [comment]
@QC-L wechat would be better, could you send your wechat id to my email sunny@sunnyxue.com? Thanks!

**Comment by QC-L** [comment]
@Sunnysit All right!

**Comment by mondaychen** [comment]
Hi @Sunnysit @QC-L 

I see #175. Thanks for the quick translation. Really appreciate your efforts.

This is yet to be decided by team, but I would strongly recommend sending PR to docs/docs_zh-cn instead of keeping it within docschina.

**Comment by drarmstr** [comment]
Looks like with #377 we're finally getting the infra in place to merge and publish these translations.

**Comment by drarmstr** [comment]
Translation already merged

**Pull request closed without merging**
