### PR TITLE
Adding a fallback for when unstable_batchedUpdates is undefined during SSR

### PR DESCRIPTION
**Pull request by leonbe02**
Resolves facebookexperimental/Recoil#2082

### CODE REVIEW

**Comment by leonbe02** [comment]
Btw, the tests that are failing in the build are the same tests that are failing on the `main` branch so I don't think they are related to my changes.

**Comment by drarmstr** [comment]
> Btw, the tests that are failing in the build are the same tests that are failing on the `main` branch so I don't think they are related to my changes.

Yeah, no worries about that, it's being fixed in another PR.

**Comment by leonbe02** [comment]
> > Btw, the tests that are failing in the build are the same tests that are failing on the `main` branch so I don't think they are related to my changes.
> 
> Yeah, no worries about that, it's being fixed in another PR.

Should I just close this PR then?

**Comment by drarmstr** [comment]
> > > Btw, the tests that are failing in the build are the same tests that are failing on the `main` branch so I don't think they are related to my changes.
> > 
> > 
> > Yeah, no worries about that, it's being fixed in another PR.
> 
> Should I just close this PR then?

I meant the failure was fixed with another commit.  Working on landing this PR now.

**Comment by andreisoare** [comment]
Looking forward to see this land, as it blocks my upgrade to Next.JS 13.

**Comment by leonbe02** [comment]
@drarmstr Are you able to re-import the PR? I just rebased it with main which flags it as needing to be re-imported.

**Comment by leonbe02** [comment]
Nevermind, it looks like my commit already got imported into `main` somehow. Should I close this PR then @drarmstr  ?

**Pull request closed without merging**
