### PR TITLE
Remove duplicate package.json

### PR DESCRIPTION
**Pull request by dustinsoftware**
This also seems to fix Jest not resolving the babelrc correctly.

### CODE REVIEW

**Comment by mondaychen** [comment]
This file is necessary for Facebook's internal repo. We can't just remove it. If this would break jest and there's no alternative fix, I can try to remove it by blacklisting it in some config file.

**Comment by dustinsoftware** [comment]
Yeah I think blacklisting it would be good with whatever sync tool is in use... as an outsider it's confusing which `package.json` file should be trusted as the source of truth for the version shipped to `npm`.

**Comment by mondaychen** [comment]
this will be done by #196

**Comment by mondaychen** [comment]
This is fixed by #196. Thanks for contributing!

**Pull request closed without merging**
