### PR TITLE
[ReactNative] Can't find variable Window exception

### PR DESCRIPTION
**Pull request by a-sane**
https://github.com/facebookexperimental/Recoil/issues/671

### CODE REVIEW

**Comment by davidmccabe** [comment]
This seems reasonable to me. Mengdi do you know what's going on with the CI?

**Comment by mondaychen** [comment]
Can we test directly against `Window`?

**Comment by mondaychen** [comment]
@davidmccabe CI has been broken for a while, I'll see if I can do a quick fix

**Comment by victoriafrench** [comment]
> Can we test directly against `Window`?

these are the scripts i have used in the past that may help with this.

```js
function getGlobalScope() {
	// browser
	if (typeof window !== 'undefined') {
		return window;
	}
	// webworkers
	if (typeof self !== 'undefined') {
		return self;
	}
	// node & deno
	if (typeof global !== 'undefined') {
		return global;
	}
	// should not be possible
	return {};
}
```

I have to put it in a function because `const globalScope = window || self || global || {};` would fail.

```js
const globalScope = getGlobalScope();

// web workers: will not have window but will have self, DOM will have both self and window in newer versions,
// they would be the same reference
const isWebWorker = Boolean(typeof window === 'undefined' && typeof self !== 'undefined');

// react native: lifted from recoil
const isReactNative = Boolean(globalScope.navigator && globalScope.navigator.product === 'ReactNative');

// node, deno: would have a global and a process, but filter out react native
const isSSR = typeof global !== 'undefined' && typeof globalScope.process !== 'undefined' && !isReactNative;

// browser: the browser dom would have recursive window and a document, would want to filter out node and dino
// in the event that a browser shim was loaded, though I don't think anyone does that anymore in unit tests. Probably
// better to just ignore isSSR and isReactNative because if they have a browser dom shim, they intend to use it?
const isDOM = Boolean(globalScope.window && globalScope.window.window && globalScope.window.document && globalScope.document && !isReactNative && !isSSR);
```

Maybe something in there would help? But I did test this and it did work in node and the browsers.

```js
function shouldNotBeFrozen(value) {
	if (isDOM && (value === globalScope.window || value instanceof globalScope.Window)) {
		return true;
	}
	return false;
}
```

**Pull request closed without merging**
