### PR TITLE
[docs/korean] Translate official document into Korean / except pages that alstn2468 translated

### PR DESCRIPTION
**Pull request by Mark-Yoo**
- [ ]  docs
    - [ ]  Introduction
        - [ ]  Motivation
        - [ ]  Core Concepts
        - [x]  Installation (@Mark-Yoo)
        - [ ]  Getting Started
    - [ ]  Basic Tutorial
        - [ ]  Intro
        - [ ]  Atoms
        - [ ]  Selectors
        - [ ]  Bonus: Performance (Didn't release)
    - [x]  Guides
        - [x]  Asynchronous Data Queries (@Mark-Yoo)
        - [x]  Atom Effects (@Mark-Yoo)
        - [x]  Testing (@Mark-Yoo)
        - [x]  Dev Tools (@Mark-Yoo)
    - [ ]  API Reference
        - [ ]  Core
            - [ ]  `<RecoilRoot />`
            - [ ]  State
                - [ ]  atom()
                - [ ]  selector()
                - [x]  Loadable (@Mark-Yoo)
                - [x]  useRecoilState() (@Mark-Yoo)
                - [x]  useRecoilValue() (@Mark-Yoo)
                - [x]  useSetRecoilState() (@Mark-Yoo)
                - [x]  useResetRecoilState() (@Mark-Yoo)
                - [x]  useRecoilValueLoadable() (@Mark-Yoo)
                - [x]  useRecoilStateLoadable() (@Mark-Yoo)
                - [ ]  isRecoilValue()
            - [x]  Snapshots
                - [x]  Snapshot (@Mark-Yoo)
                - [x]  useRecoilTransactionObserver() (@Mark-Yoo)
                - [x]  useRecoilSnapshot() (@Mark-Yoo)
                - [x]  useGotoRecoilSnapshot() (@Mark-Yoo)
            - [x]  useRecoilCallback() (@Mark-Yoo)
            - [x]  Misc
                - [x]  useRecoilBridgeAcrossReactRoots() (@jung-han)
        - [x]  Utils
            - [x]  atomFamily() (@jung-han)
            - [x]  selectorFamily() (@jung-han)
            - [x]  constSelector() (@jung-han)
            - [x]  errorSelector() (@jung-han)
            - [x]  waitForAll() (@jung-han)
            - [x]  waitForAny() (@jung-han)
            - [x]  waitForNone() (@jung-han)
            - [x]  noWait() (@jung-han)

### CODE REVIEW

**Comment by jung-han** [comment]
@Mark-Yoo 
Hi. Are you working alone? If there is a part that has not been translated, I would like to help you out. How can I participate?

**Comment by Mark-Yoo** [comment]
@jung-han Hi! Yes, I'm working alone now. I'm working on pages except alstn2468 translated. so basically Misc and Utils sections left. I would love to get some help from you if you are available. I'm actually working on `atomFamliy.md`, so whichever pages left are open for translation.

what you should do before contribute is to go register CLA
(See https://github.com/facebookexperimental/Recoil to follow the Contribution Guide)

**Comment by jung-han** [comment]
@Mark-Yoo 
Good! I will work on a branch in the [repository](https://github.com/Mark-Yoo/Recoil/tree/docs) and review it.

**Comment by Mark-Yoo** [comment]
@jung-han You are invited as collaborator. Please keep on check which part you are working on and which part you finished translating 👍

**Comment by jung-han** [comment]
@Mark-Yoo 
If time is okay, please check PR! It looks like we've translated everything. Is it right?

**Comment by Mark-Yoo** [comment]
@jung-han Yes! but Recoil is on development so please keep on watch for changes and new functions which can be added to documents. :) I'll also check periodically.

**Comment by drarmstr** [comment]
Note some new doc changes for upcoming 0.2 are here: https://github.com/drarmstr/Recoil/tree/docs_0_2/docs

**Comment by Mark-Yoo** [comment]
@drarmstr I'll check what's new :)

**Comment by alstn2468** [comment]
@Mark-Yoo Thank you for finishing the remaining works :-)

**Comment by Mark-Yoo** [comment]
@alstn2468 we've done what has to be done :) thanks you for all this translation to be started 👍

**Comment by drarmstr** [comment]
We'd love to be able to merge these translations, but we don't yet have a link or index for the different translations from the documentation side.  Would anyone here be interested in adding a link or tab on the main docs page to the translations so we can finally merge them?

**Comment by jung-han** [comment]
@drarmstr Can you give me some code to use as an example? It would be nice to let us know where it appears on the page.

**Comment by drarmstr** [comment]
@jung-han - It doesn't appear anywhere right now... ;)  We're hoping for some help if someone has time to investigate and do a PR for the `docs` branch to add the link and make a new page with the list of translations.  Maybe putting the link in the footer would be the right place.

**Comment by Mark-Yoo** [comment]
@drarmstr Hmm... We'll let you know if we find a way to do it. :) Never try make pages for the Official Page, so gotta find the way before I try :)

**Comment by Mark-Yoo** [comment]
@drarmstr Hmm... We'll let you know if we find a way to do it. :) I've never tried make pages for the Official Page, so gotta find the way before I try :)

**Comment by alstn2468** [comment]
@Mark-Yoo I found the translation part in docusaurus document. It would be nice to see.

https://docusaurus.io/docs/en/translation

**Comment by Mark-Yoo** [comment]
@alstn2468 Thanks! I'll read it :)

**Comment by drarmstr** [comment]
Any luck with figuring out the right approach for publishing the translations @Mark-Yoo?

**Comment by Mark-Yoo** [comment]
@drarmstr I'm working on urgent project now... so gonna need just a bit more time DX
sorry to drag...

**Comment by Mark-Yoo** [comment]
@drarmstr I've read the page that @alstn2468 sent me and it was about using Crowdin to open the project for translation. Seems like the project has to be created upon Crowdin to get translators. Guess it's not the way we've been looking for... :(

I'm new to Docusaurus so probably need to figure out surfing internet or something.

I'm currently busy due to urgent project. Sorry being late and dragging...

**Comment by fguitton** [comment]
@Mark-Yoo, @drarmstr, @alstn2468. I'm just added the configuration for the FR repo based on Docusaurus docs. See my https://github.com/facebookexperimental/Recoil/pull/377#issuecomment-812531868. No Crowdin required. Would that solution be workable ?

**Comment by Mark-Yoo** [comment]
@fguitton I think that would be workable. Thanks! I'm just begin really busy, can't even focus reading Docusaurus documents... thanks for help! I really appreciate!

**Comment by alstn2468** [comment]
@Mark-Yoo If you're busy working, what can I do for you?
I don't know how it would be good to work because the PR that worked on the work was separated.

**Comment by ChobobDev** [comment]
@Mark-Yoo  I can also give my hand for you.

**Comment by Mark-Yoo** [comment]
@alstn2468 @ChobobDev Thanks guys! Guess it was my mistake separate PR from @alstn2468 . I'll combine my translations into @alstn2468 's PR to make things easier.

I'm currently reading [Docusaurus Internationalization](https://docusaurus.io/docs/i18n/introduction) which is probably @fguitton refer to. Will you set the structure before I fork your repo, @alstn2468 ?

**Comment by alstn2468** [comment]
Okay, then I'll refer to [#377(comment)](https://github.com/facebookexperimental/Recoil/pull/377#issuecomment-812531868) and tell you after I finish setting it up at my fork repo.

**Comment by Mark-Yoo** [comment]
@alstn2468 Thank you! I appreciate!

**Comment by alstn2468** [comment]
@Mark-Yoo  @ChobobDev @jung-han 

The internationalization setup was completed through the 36fa13c commit.
I have confirmed that the command `yarn start -- --locale kr` is executed normally.
I think the work to be carried out will be as follows.

1. Combine separated PRs.
2. Update missing translation, synchronizing the latest documents.
3. Adding internationalized translation key data.

Can I add access to my forked repository?

**Comment by Mark-Yoo** [comment]
@alstn2468 Nice! Please add me as collaborator so that I can make new PR's. Thanks for your work :)

**Comment by Mark-Yoo** [comment]
@alstn2468 I've pushed and merged my parts :) should we wait @jung-han for his part?

**Comment by jung-han** [comment]
@Mark-Yoo @alstn2468 
Can I put the translation file I was working on in that branch?
If right, i'll check it out in the evening and get it working.

**Comment by drarmstr** [comment]
Sounds like all Korean translation has been merged into #18 and this PR can be closed.

**Comment by drarmstr** [comment]
Duplicate of #18

**Comment by Mark-Yoo** [comment]
This PR is now closed. All Korean translation merged into #18.

**Pull request closed without merging**
